const ADD_PROFILEINFO = 'ADD_PROFILEINFO';
const ADD_ADDRESSINFO = 'ADD_ADDRESSINFO';
const ADD_QUALIFICATIONINFO = 'ADD_QUALIFICATIONINFO';
const ADD_REGISTATIONINFO = 'ADD_REGISTATIONINFO';
const EDIT_PROFILEINFO = 'EDIT_PROFILEINFO';
const EDIT_ADDRESSINFO = 'EDIT_ADDRESSINFO';
const EDIT_QUALIFICATIONINFO = 'EDIT_QUALIFICATIONINFO';
const EDIT_REGISTATIONINFO = 'EDIT_REGISTATIONINFO';

export {
  ADD_PROFILEINFO,
  ADD_ADDRESSINFO,
  ADD_QUALIFICATIONINFO,
  ADD_REGISTATIONINFO,
  EDIT_PROFILEINFO,
  EDIT_ADDRESSINFO,
  EDIT_QUALIFICATIONINFO,
  EDIT_REGISTATIONINFO,
};
